### PR TITLE
Fix OpenAPI spec should have `/` for the path when the service path is `.` 

### LINKED ISSUE #120: Open API spec should have `/` for the path when the service path is `.`
**Description:**
In a simple service with the resource as `post .` , when we generate the Open API spec, it will be generated with a `/.`  as the path. This should be generated as `/`

Sample service:
```ballerina
import ballerina/http;

service on new http:Listener(8090) {
    resource function post .(http:Caller caller, http:Request req) returns error? {
        checkpanic caller->respond(check req.getTextPayload());
    }
}
```

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/main/java/org/ballerinalang/ballerina/service/OpenApiResourceMapper.java [hunk 1]
```diff
@@ -498,7 +498,13 @@ private void createParametersModel(FunctionDefinitionNode resource, Operation op
      */
     private void parseResourceConfigAnnotationAttachment(FunctionDefinitionNode resource, OperationAdaptor operation) {
 
-            operation.setPath(resource.relativeResourcePath().get(0).toString());
+        String path = resource.relativeResourcePath().get(0).toString();
+        if (path.equals(".") || path.equals("/")) {
```
Comment (hemikak) [inline openapi-cli/src/main/java/org/ballerinalang/ballerina/service/OpenApiResourceMapper.java:502]: Do we need the `path.equals("/")` condition ? since `path` would already be `/`.

File: openapi-cli/src/test/resources/ballerina-to-openapi/path_scenario02.bal [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+ listener http:Listener helloEp = new (9090);
+
+ service /payloadV on helloEp {
+
+     resource function post . (http:Caller caller, http:Request request) {
+
+     }
+     resource function get . (http:Caller caller, http:Request request) {
+
+          }
```
Comment (hemikak) [inline openapi-cli/src/test/resources/ballerina-to-openapi/path_scenario02.bal:12]: indentation error ?

File: openapi-cli/src/main/java/org/ballerinalang/ballerina/service/OpenApiResourceMapper.java [hunk 3]
```diff
@@ -556,6 +562,9 @@ private String generateRelativePath(FunctionDefinitionNode resource) {
                 if (node instanceof ResourcePathParameterNode) {
                     ResourcePathParameterNode pathNode = (ResourcePathParameterNode) node;
                     relativePath = relativePath + "{" + pathNode.paramName() + "}";
+                } else if ((resource.relativeResourcePath().size() == 1) &&
+                        (node.toString().trim().equals(".") || node.toString().trim().equals("/"))) {
```
Comment (hemikak) [inline openapi-cli/src/main/java/org/ballerinalang/ballerina/service/OpenApiResourceMapper.java:566]: Is it the same as above comment ?

File: openapi-cli/src/main/java/org/ballerinalang/ballerina/service/OpenApiResourceMapper.java (hunk 1 above)
Comment (lnash94) [reply openapi-cli/src/main/java/org/ballerinalang/ballerina/service/OpenApiResourceMapper.java]: we can remove that condition, because `post /` type scenarios are invalid in the resource type.

**Review by hemikak — APPROVED** [review]
