### PR TITLE
Fix Convert Ballerina to OpenAPI command implementation from swagger v2 to swagger v3 

### LINKED ISSUE #54: Add respones payload handle to ballerina-to-OpenAPI command
**Description:**
Add the response handling to ballerina to openapi command
- **Response payload**
  -  -[x] Simple types 
  -  -[x] Error types
  -  -[x] Simple records
  -  -[x] Nested records

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### LINKED ISSUE #119: Convert Ballerina to OpenAPI command implementation from swagger v2 to swagger v3
**Description:**
Convert the swagger implementation version 2 to 3 in ballerina to openapi the command

- [x] Mapping listernsers
- [x] Mapping service details
- [x] Mapping path details
- [x] Mapping operation details
- [x] Mapping parameter details
- [x] Mapping requestBody details
- [ ] Mapping response details
- [x] Mapping record schema details to components. 

 Basically, support the ballerina service and resource functions in the following documentation that enable with the command openapi to ballerina.
[openapi to ballerina](https://docs.google.com/document/d/1ubuKZ9GXRP0_b_vy8NLKIvdbQsyhTIcRql9HPmITA-I/edit?ts=603730bd#heading=h.r0bjcdjhgpj)
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by lnash94**
Fix #54 

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/main/java/org/ballerinalang/ballerina/Constants.java [hunk 1]
```diff
@@ -51,6 +51,15 @@
...
     public static final String TYPEREFERENCE = "typeReference";
+    public static final String HTTP_HEADER = "http:Header";
+    public static final String BYTE_ARRAY = "byte[]";
+    public static final String OCTET_STREAM = "octet-stream";
+    public static final String XML = "xml";
+    public static final String JSON = "json";
+    public static final String PLAIN = "plain";
+
+
+
```
Comment (hemikak) [inline openapi-cli/src/main/java/org/ballerinalang/ballerina/Constants.java:62]: Shall we remove this empty space ?

**Review by hemikak — APPROVED** [review]

**Review by hevayo — APPROVED** [review]
