### PR TITLE
Fix create syntax tree based client generators to the openapi to ballerina command 

### LINKED ISSUE #129: Create syntax tree based client generators to the openapi to ballerina command
**Description:**
$Subject

- [x] Finalise the client for generating documentation
- [x] Implement client Class with default value
- [x] Implement process to generate operationID for operation which hasn't operationID
- [x] Implement client for simple operation
- [x] Implement client for query parameters
- [x] Implement client for path parameters
- [x] Implement client for header parameters
- [x] Implement client for request body parameters
- [x] Implement client for dirrefent response type 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### LINKED ISSUE #189: Disable Ballerina to OpenAPI return type has record array test
**Description:**
$Subject

Affect of this [https://github.com/ballerina-platform/ballerina-standard-library/issues/1276,](https://github.com/ballerina-platform/ballerina-standard-library/issues/1276) , ballerina to openapi record array response test is disabled 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by lnash94**
Fix #189

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/main/java/org/ballerinalang/generators/GeneratorConstants.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
+package org.ballerinalang.generators;
```
Comment (hemikak) [inline openapi-cli/src/main/java/org/ballerinalang/generators/GeneratorConstants.java:1]: Add license header

File: openapi-cli/src/main/resources/templates/client/client_template.bal [hunk 2]
```diff
@@ -0,0 +1,7 @@
+public client class Client {
+   public http:Client clientEp;
+   public function init(string serviceUrl = "http://localhost:9090/v1", http:ClientConfiguration httpClientConfig = {}) returns error? {
+       http:Client httpEp = check new (serviceUrl, httpClientConfig);
+       self.clientEp = httpEp;
+   }
+   }
```
Comment (hemikak) [inline openapi-cli/src/main/resources/templates/client/client_template.bal:7]: Fix indentation and add new line

File: openapi-cli/src/test/java/org/ballerinalang/generators/BallerinaClientGeneratorTests.java [hunk 3]
```diff
@@ -0,0 +1,90 @@
+package org.ballerinalang.generators;
```
Comment (hemikak) [inline openapi-cli/src/test/java/org/ballerinalang/generators/BallerinaClientGeneratorTests.java:1]: Add copyright header

File: openapi-cli/src/test/java/org/ballerinalang/openapi/CodeGeneratorTest.java [hunk 4]
```diff
@@ -123,7 +123,7 @@ public void generateClientwithRequestBody() {
         }
     }
 
-    @Test(description = "Test Ballerina skeleton generation")
+    @Test(description = "Test Ballerina skeleton generation", enabled = false)
```
Comment (hemikak) [inline openapi-cli/src/test/java/org/ballerinalang/openapi/CodeGeneratorTest.java:126]: Do we need this ?

File: openapi-cli/src/test/resources/expected_gen/generate_client.bal [hunk 5]
```diff
@@ -1,58 +1,61 @@
...
-public client class openapipetstoreClient {
+public client class Client {
     public http:Client clientEp;
-    public openapipetstoreClientConfig config;
-
-    public function init(openapipetstoreClientConfig config) {
-        http:Client httpEp = checkpanic new(config.serviceUrl, {auth: config.clientConfig.auth, cache:
-            config.clientConfig.cache});
+    public function init(string serviceUrl = "http://petstore.openapi.io/v1", http:ClientConfiguration httpClientConfig= {})
+    returns error?{
```
Comment (hemikak) [inline openapi-cli/src/test/resources/expected_gen/generate_client.bal:8]: Need a space after `?`

File: openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaClientGenerator.java [hunk 6]
```diff
@@ -0,0 +1,1262 @@
...
+
+    public static SyntaxTree generateSyntaxTree(Path definitionPath, Filter filter) throws IOException,
+            BallerinaOpenApiException {
+        imports.clear();
+        isQuery = false;
+        // Summaries OpenAPI details
+        OpenAPI openAPI = getBallerinaOpenApiType(definitionPath);
+        //Filter serverUrl
+        List<Server> servers = openAPI.getServers();
+        server = servers.get(0);
```
Comment (hemikak) [inline openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaClientGenerator.java:204]: If there are no servers listed ?

File: openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaClientGenerator.java [hunk 7]
```diff
@@ -0,0 +1,1262 @@
...
+            if (requestBody.getContent() != null) {
+                setRequestBodyParameters(parameterList, requestBody);
+                parameterList.add(comma);
+            }
+        }
+    }
+
+/*
+ * Create query parameters.
+ */
```
Comment (hemikak) [inline openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaClientGenerator.java:664]: Not properly indented

File: openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaClientGenerator.java (hunk 6 above)
Comment (lnash94) [reply openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaClientGenerator.java:204]: Swagger provides '/' for when the contract missing the server section. In case the user is missing to fill the server section with the URLs, that time swagger parser will generate the error mentioning contract is not a valid contract.

File: openapi-cli/src/test/java/org/ballerinalang/openapi/CodeGeneratorTest.java (hunk 4 above)
Comment (lnash94) [reply openapi-cli/src/test/java/org/ballerinalang/openapi/CodeGeneratorTest.java]: we can enable it

File: openapi-cli/src/main/java/org/ballerinalang/generators/GeneratorConstants.java [hunk 8]
```diff
@@ -0,0 +1,92 @@
...
+                    "committed", "const", "continue", "decimal", "else", "error", "external", "fail", "final",
+                    "finally", "float", "flush", "fork", "function", "future", "handle", "if", "import", "in", "int",
+                    "is", "join", "json", "listener", "lock", "match", "new", "object", "OBJECT_INIT", "onretry",
+                    "parameter", "panic", "private", "public", "record", "remote", "resource", "retries", "retry",
+                    "return", "returns", "service", "source", "start", "stream", "string", "table", "transaction",
+                    "try", "type", "typedesc", "typeof", "trap", "throw", "wait", "while", "with", "worker", "var",
+                    "version", "xml", "xmlns", "BOOLEAN_LITERAL", "NULL_LITERAL", "ascending", "descending", "foreach",
+                    "map", "group", "from", "default", "field", "limit", "as", "on", "isolated", "readonly",
+                    "distinct", "where", "select", "do", "transactional", "commit", "enum", "base16", "base64",
+                    "rollback", "configurable",  "class", "module", "never", "outer", "order", "null", "key", "let",
```
Comment (hevayo) [inline openapi-cli/src/main/java/org/ballerinalang/generators/GeneratorConstants.java:75]: We need to derive this from parser lexer class. Can send it as a separate PR

File: openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaClientGenerator.java [hunk 9]
```diff
@@ -0,0 +1,1263 @@
...
+                statementsList.add(getMapForParameters(queryParameters, "map<anydata>", "queryParam"));
+                // Add updated path
+                ExpressionStatementNode updatedPath = getSimpleExpressionStatementNode("path = path + " +
+                        "getPathForQueryParam(queryParam)");
+                statementsList.add(updatedPath);
+                isQuery = true;
+            }
+            if (!headerParameters.isEmpty()) {
+                statementsList.add(getMapForParameters(headerParameters, "map<string|string[]>",
+                        "accHeaders"));
```
Comment (hemikak) [inline openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaClientGenerator.java:873]: addHeaders ?

**Review by hevayo — APPROVED** [review]

File: openapi-cli/src/test/resources/ballerina-to-openapi/nestedRecord_payload_service.bal [hunk 10]
```diff
@@ -15,4 +15,5 @@ type Pet record {
  service /payloadV on helloEp {
      resource function post hi(http:Caller caller, http:Request request, @http:Payload {} Dog payload) {
 
-     }}
+     }
+     }
```
Comment (hemikak) [inline openapi-cli/src/test/resources/ballerina-to-openapi/nestedRecord_payload_service.bal:19]: Needs formatting ?

**Review by hemikak — APPROVED** [review]
