### PR TITLE
[Service] Refactor OpenAPI to Ballerina service generation code structure

### LINKED ISSUE #394: Refactor OpenAPI to Ballerina service generation code structure
**Description:**
Enhance the code readability align the code with the OOP concept.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### LINKED ISSUE #428: Issue with serverURL mapping in OpenAPI to resource endpoints
**Description:**
```openapi
servers:
  - url: https://api.sendgridf.com/v3
```
Here port is not given in the openapi 
```ballerina
listener  http:Listener  ep0  = new (9090, config  = {host: "localhost"});
```
Expected generation
```ballerina
listener  http:Listener  ep0  = new (443, config  = {host: "api.sendgridf.com"});
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### LINKED ISSUE #530: 204 response code generated as http:Ok for services
**Description:**
$subject
```yaml
      responses:
        '204':
          description: Email successfully sent
```

### PR DESCRIPTION
**Pull request by lnash94**
Fix #530 
Fix #428

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ListenerGenerator.java [hunk 1]
```diff
@@ -0,0 +1,168 @@
...
+        }
+        return getListenerDeclarationNode(port, host, " ep0");
+    }
+
+    public static ListenerDeclarationNode getListenerDeclarationNode(Integer port, String host, String ep) {
+
+        // Take first server to Map
+        Token listenerKeyword = AbstractNodeFactory.createIdentifierToken("listener");
+        // Create type descriptor
+        Token modulePrefix = AbstractNodeFactory.createIdentifierToken(" http");
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ListenerGenerator.java:119]: If you need to consider leading/trailing whitespaces when creating tokens, you can use `AbstractNodeFactory.createIdentifierToken(String text, MinutiaeList leadingMinutiae, MinutiaeList trailingMinutiae);`. Revisit all other similar places to avoid defining constants with whitespaces.

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ReturnTypeGenerator.java [hunk 2]
```diff
@@ -0,0 +1,292 @@
...
+            } else {
+                while (responseIter.hasNext()) {
+                    Map.Entry<String, ApiResponse> response = responseIter.next();
+                    if (response.getValue().getContent() == null && response.getValue().get$ref() == null) {
+                        String code = GeneratorConstants.HTTP_CODES_DES.get(response.getKey().trim());
+                        // Scenario 01: Response has single response without content type
+                        QualifiedNameReferenceNode statues = getQualifiedNameReferenceNode("http", code);
+                        returnNode = createReturnTypeDescriptorNode(returnKeyWord, annotations, statues);
+                    } else if (response.getValue().getContent() != null) {
+                        if (response.getKey().trim().equals("200")) {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ReturnTypeGenerator.java:100]: Shouldn't we use constants for all the known HTTP codes?

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceGenerationUtils.java [hunk 3]
```diff
@@ -0,0 +1,217 @@
...
+            } else {
+                identifier = identifier.replaceAll(GeneratorConstants.ESCAPE_PATTERN, "\\\\$1");
+                if (identifier.endsWith("?")) {
+                    if (identifier.charAt(identifier.length() - 2) == '\\') {
+                        StringBuilder stringBuilder = new StringBuilder(identifier);
+                        stringBuilder.deleteCharAt(identifier.length() - 2);
+                        identifier = stringBuilder.toString();
+                    }
+                    if (BAL_KEYWORDS.stream().anyMatch(Optional.ofNullable(identifier)
+                            .filter(sStr -> sStr.length() != 0)
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceGenerationUtils.java:81]: Lets use more meaningful variable names in here

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceGenerationUtils.java [hunk 4]
```diff
@@ -0,0 +1,217 @@
...
+            case "text/plain":
+                identifierToken = createIdentifierToken("string");
+                return createSimpleNameReferenceNode(identifierToken);
+            case "application/octet-stream":
+                return createArrayTypeDescriptorNode(createBuiltinSimpleNameReferenceNode(
+                        null, createIdentifierToken("byte")), createToken(SyntaxKind.OPEN_BRACKET_TOKEN),
+                        null, createToken(SyntaxKind.CLOSE_BRACKET_TOKEN));
+            default:
+                identifierToken = createIdentifierToken("json");
+                return createSimpleNameReferenceNode(identifierToken);
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceGenerationUtils.java:214]: Lets use constants/enums for Ballerina built-in types. Please revisit other related places as well

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java [hunk 5]
```diff
@@ -756,7 +756,7 @@ private VariableDeclarationNode getMapForParameters(List<Parameter> parameters,
 
     private boolean checkImportDuplicate(List<ImportDeclarationNode> imports, String module) {
         for (ImportDeclarationNode importModule:imports) {
-            if (importModule.toString().equals("importballerina/" + module + ";")) {
+            if (importModule.toString().equals("import ballerina/" + module + ";")) {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java:759]: Shall we only assert the module name (and the org name too?), instead of doing string comparison using the whole source code of the import node?

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ListenerGenerator.java [hunk 6]
```diff
@@ -0,0 +1,168 @@
...
+                host = url.getHost();
+                basePath = url.getPath();
+                port = url.getPort();
+                boolean isHttps = "https".equalsIgnoreCase(url.getProtocol());
+
+                if (isHttps) {
+                    port = port == -1 ? httpsPort : port;
+                } else {
+                    port = port == -1 ? httpPort : port;
+                }
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ListenerGenerator.java:97]: This can be simplified as below.
```suggestion
                if (port < 0) {
                    port = isHttps ? httpsPort : httpPort;
                }
```

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java (hunk 5 above)
Comment (lnash94) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java]: Fix with  d244c68

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java [hunk 7]
```diff
@@ -92,7 +94,11 @@
 public class GeneratorUtils {
 
     public static ImportDeclarationNode getImportDeclarationNode(String orgName, String moduleName) {
-        Token importKeyword = AbstractNodeFactory.createIdentifierToken("import ");
+        Minutiae whitespace = AbstractNodeFactory.createWhitespaceMinutiae(" ");
+        MinutiaeList leading = AbstractNodeFactory.createEmptyMinutiaeList();
+        MinutiaeList trailing = AbstractNodeFactory.createMinutiaeList(whitespace);
+
+        Token importKeyword = AbstractNodeFactory.createIdentifierToken("import", leading, trailing);
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java:101]: Please use an util method instead of duplicating this minutiae list creation in multiple places.

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java [hunk 8]
```diff
@@ -756,7 +757,12 @@ private VariableDeclarationNode getMapForParameters(List<Parameter> parameters,
 
     private boolean checkImportDuplicate(List<ImportDeclarationNode> imports, String module) {
         for (ImportDeclarationNode importModule:imports) {
-            if (importModule.toString().equals("import ballerina/" + module + ";")) {
+            StringBuilder moduleBuilder = new StringBuilder();
+            for (IdentifierToken identifierToken : importModule.moduleName()) {
+                moduleBuilder.append(identifierToken.toString().trim());
+            }
+            if (BALLERINA.equals(importModule.orgName().get().toString().trim().replace("/", "")) &&
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java:764]: You dont have to do a string replacement to remove the trailing separator token. `io.ballerina.compiler.syntax.tree.ImportOrgNameNode` contains a separate API to get the orgname without the separator.

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java [hunk 9]
```diff
@@ -608,9 +607,10 @@ public static String buildUrl(String absUrl, ServerVariables variables) {
         return url;
     }
 
-    public static MinutiaeList getMinutiaes() {
+    public static MinutiaeList getSingleWSMinutiae() {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java:610]: Lets make this private

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java [hunk 10]
```diff
@@ -608,9 +607,10 @@ public static String buildUrl(String absUrl, ServerVariables variables) {
...
         Minutiae whitespace = AbstractNodeFactory.createWhitespaceMinutiae(" ");
         MinutiaeList leading = AbstractNodeFactory.createMinutiaeList(whitespace);
         return leading;
     }
+    public static final MinutiaeList SINGLE_WS_MINUTIAE = getSingleWSMinutiae();
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java:615]: Usually we keep class variable definitions before the method declarations.

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ListenerGenerator.java [hunk 11]
```diff
@@ -0,0 +1,160 @@
...
+import static io.ballerina.openapi.generators.GeneratorUtils.SINGLE_WS_MINUTIAE;
+
+/**
+ * This util class for processing the mapping in between openAPI server section with ballerina listeners.
+ *
+ * @since 2.0.0
+ */
+public class ListenerGenerator {
+    private static final int httpPort = 80;
+    private static final int httpsPort = 443;
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ListenerGenerator.java:59]: Please use upper-case for constant variable names

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java [hunk 12]
```diff
@@ -0,0 +1,178 @@
...
+        return createRequiredParameterNode(annotation, typeName, paramName);
+    }
+
+    private SeparatedNodeList<MappingFieldNode> fillRequestAnnotationValues(Token comma, List<Node> literals,
+                                                                            IdentifierToken mediaType,
+                                                                            HashSet<Map.Entry<String,
+                                                                                    MediaType>> equalDataType) {
+        Minutiae whitespace = AbstractNodeFactory.createWhitespaceMinutiae(" ");
+        MinutiaeList leading = AbstractNodeFactory.createMinutiaeList(whitespace);
+        MinutiaeList trailing = AbstractNodeFactory.createMinutiaeList(whitespace);
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java:112]: Please use the util

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ParametersGenerator.java [hunk 13]
```diff
@@ -0,0 +1,250 @@
...
+            BuiltinSimpleNameReferenceNode rTypeName = createBuiltinSimpleNameReferenceNode(null, name);
+            return createRequiredParameterNode(annotations, rTypeName, parameterName);
+        }
+    }
+
+    // Create ArrayTypeDescriptorNode using Schema
+    private  ArrayTypeDescriptorNode getArrayTypeDescriptorNode(Schema<?> items) {
+        Minutiae whitespace = AbstractNodeFactory.createWhitespaceMinutiae(" ");
+        MinutiaeList leading = AbstractNodeFactory.createMinutiaeList(whitespace);
+        MinutiaeList trailing = AbstractNodeFactory.createMinutiaeList(whitespace);
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ParametersGenerator.java:243]: Please use the util

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceGenerationUtils.java [hunk 14]
```diff
@@ -0,0 +1,228 @@
...
+        }
+        return traversUnion;
+    }
+
+    /**
+     * Generate typeDescriptor for application/json type.
+     */
+    public static TypeDescriptorNode getIdentifierTokenForJsonSchema(Schema schema) throws BallerinaOpenApiException {
+        Minutiae whitespace = AbstractNodeFactory.createWhitespaceMinutiae(" ");
+        MinutiaeList trailing = AbstractNodeFactory.createMinutiaeList(whitespace);
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceGenerationUtils.java:152]: Please use the util

**Review by NipunaRanasinghe — APPROVED** [review]
