### PR TITLE
[BallerinaToOAS] Fix resource `json` type request payload mapping with improvements

### LINKED ISSUE #427: Improve resource  `json` type request payload mapping with  OpenAPI specification
**Description:**
Ballerina resource function
```ballerina
resource function post v1(@http:Payload json payload) returns http:OK {
}
```
Currently generated openAPI code
```openapi
v1:
 post:
   operationId: operation1_post_v1
   requestBody:
     content:
       application/json:
          schema:
            type: object
```
Suggested code generation

```openapi
v1:
 post:
   operationId: operation1_post_v1
   requestBody:
     content:
       application/json:
          schema: {}
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by lnash94**
- Providing the default schema when the request body has only `json` as a type
- Fix nullable array type field mapping issue
```ballerina
type Link record {|
    string[]? mediaTypes?;
|};
```
expected output
```openapi
components:
  schemas:
    Link:
        mediaTypes:
          type: array
          nullable: true
          items:
            type: string
```

- Fix nullable query parameter handling

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 1]
```diff
@@ -303,8 +303,12 @@ private void mapArrayToArraySchema(Map<String, Schema> schema, RecordFieldSymbol
             ArrayTypeSymbol arrayTypeSymbol = (ArrayTypeSymbol) symbol;
             symbol = arrayTypeSymbol.memberTypeDescriptor();
         }
-        //handle record field has nested record array type ex: Tag[] tags
+        //handle record field has reference record array type ex: Tag[] tags
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:306]:
```suggestion
        // handle record fields having reference record array type (ex: Tag[] tags)
```

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 2]
```diff
@@ -325,6 +329,26 @@ private void mapArrayToArraySchema(Map<String, Schema> schema, RecordFieldSymbol
         }
     }
 
+    /**
+     * This function uses to map union type of BUNION type ex: string[]? name.
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:333]:
```suggestion
     * This function is used to map union type of BUNION type ex: string[]? name.
```

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 3]
```diff
@@ -303,8 +303,12 @@ private void mapArrayToArraySchema(Map<String, Schema> schema, RecordFieldSymbol
             ArrayTypeSymbol arrayTypeSymbol = (ArrayTypeSymbol) symbol;
             symbol = arrayTypeSymbol.memberTypeDescriptor();
         }
-        //handle record field has nested record array type ex: Tag[] tags
+        //handle record field has reference record array type ex: Tag[] tags
         Schema symbolProperty  = ConverterCommonUtils.getOpenApiSchema(symbol.typeKind().getName());
+        //handle record field has ex:string[]? name
+        if (symbol.typeKind() == TypeDescKind.UNION) {
+            symbolProperty = getSchemaForUnionType((UnionTypeSymbol) symbol, symbolProperty);
+        }
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:311]: Shouldn't we update the comment as we are handling union types in here?

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 4]
```diff
@@ -325,6 +329,26 @@ private void mapArrayToArraySchema(Map<String, Schema> schema, RecordFieldSymbol
         }
     }
 
+    /**
+     * This function uses to map union type of BUNION type ex: string[]? name.
+     *
+     * TODO: Map for different array type unions ex: float|int[] ids, float|int[]? ids
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:335]:
```suggestion
     * TODO: Map for different array type unions (ex: float|int[] ids, float|int[]? ids)
```

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 5]
```diff
@@ -325,6 +329,26 @@ private void mapArrayToArraySchema(Map<String, Schema> schema, RecordFieldSymbol
...
+     * `string[]? name` here it takes union member types as array and nil,fix should do with array type and map to
+     * oneOf OAS.
+     */
+    private Schema getSchemaForUnionType(UnionTypeSymbol symbol, Schema symbolProperty) {
+        List<TypeSymbol> typeSymbols = symbol.userSpecifiedMemberTypes();
+        for (TypeSymbol typeSymbol: typeSymbols) {
+            if (typeSymbol.typeKind() == TypeDescKind.ARRAY) {
+                TypeSymbol arrayType = ((ArrayTypeSymbol) typeSymbol).memberTypeDescriptor();
+                symbolProperty = ConverterCommonUtils.getOpenApiSchema(arrayType.typeKind().getName());
+            } else if (!(typeSymbol.typeKind() == TypeDescKind.NIL)) {
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:345]:
```suggestion
            } else if (typeSymbol.typeKind() != TypeDescKind.NIL) {
```

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM
