### PR TITLE
Fix LS breaks when openAPI is imported

### LINKED ISSUE #244: LS breaks when openapi is imported
**Description:**
LS breaks when openapi module is imported and use to annotate service. Please try with attached source.
[main.bal.txt](https://github.com/ballerina-platform/ballerina-openapi/files/6489312/main.bal.txt)

```
io.ballerina.projects.ProjectException: The compiler extension in package 'ballerina:openapi:0.9.0-beta.1' failed to complete. null
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxNodeAnalysisTask.perform(CodeAnalyzerManager.java:230)
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxTreeVisitor.runAnalysisTasks(CodeAnalyzerManager.java:485)
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxTreeVisitor.visitSyntaxNode(CodeAnalyzerManager.java:472)
...
Caused by: java.lang.NullPointerException
	at io.ballerina.openapi.validator.ResourceWithOperation.summarizeOpenAPI(ResourceWithOperation.java:357)
	at io.ballerina.openapi.validator.ResourceWithOperation.filterOpenapi(ResourceWithOperation.java:59)
...
```

**Affected Versions:**
slbeta1-rc1

### PR DESCRIPTION
**Pull request by lnash94**
Fix [https://github.com/wso2-enterprise/choreo/issues/4126](https://github.com/wso2-enterprise/choreo/issues/4126)
Fix [https://github.com/wso2-enterprise/choreo/issues/4129](https://github.com/wso2-enterprise/choreo/issues/4129)

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-validator/src/main/java/io/ballerina/openapi/validator/ErrorMessages.java [hunk 1]
```diff
@@ -177,4 +177,10 @@
         return error;
     }
 
+    static String[] contactPathEmpty() {
```
Comment (hemikak) [inline openapi-validator/src/main/java/io/ballerina/openapi/validator/ErrorMessages.java:180]: type: contractPathEmpty

File: openapi-validator/src/main/java/io/ballerina/openapi/validator/ErrorMessages.java [hunk 2]
```diff
@@ -177,4 +177,10 @@
...
+        String[] error = new String[2];
+        error[0] = ValidatorErrorCode.BAL_OPENAPI_VALIDATOR_0020;
+        error[1] = "Contract file can not be empty.";
```
Comment (hemikak) [inline openapi-validator/src/main/java/io/ballerina/openapi/validator/ErrorMessages.java:183]: OpenAPI contract file can not be empty.

would be more specific.

File: openapi-validator/src/main/java/io/ballerina/openapi/validator/ErrorMessages.java [hunk 3]
```diff
@@ -177,4 +177,10 @@
         return error;
     }
 
+    static String[] contractPathEmpty() {
+        String[] error = new String[2];
+        error[0] = ValidatorErrorCode.BAL_OPENAPI_VALIDATOR_0020;
+        error[1] = "Given openAPI contract file path is an empty string.";
```
Comment (hemikak) [inline openapi-validator/src/main/java/io/ballerina/openapi/validator/ErrorMessages.java:183]: Make the O in openAPI capital

**Review by hemikak — APPROVED** [review]
