### PR TITLE
Fix implement the TypeInclusion mapping with `allOf` data binding in openAPI spec

### LINKED ISSUE #400: Implement the Type inclusion mapping with allOf data binding in openAPI spec
**Description:**
**Ballerina record example**
```ballerina
type Link record {|
   string rel;
   string href;
   string[] mediaTypes?;
   Action[] actions?;
|};

type Links record {|
   Link[] links;
|};

type Reservation record {|
   string roomId;
   int count;
   string startDate;
   string endDate;
|};

type ReservationReceipt record {|
   *Links;
   string id;
   string expiryDate;
   string lastUpdated;
   Reservation[] rooms;
|};
```
**Expected swagger generation**
```openapi
components: 
  schemas:
   Reservation:
    type: object
    properties:
      roomId:
        type: string
      count:
        type: integer
      startDate:
        type: string
      endDate:
        type: string   
          
   Link:
    type: object
    properties:
     rel:
      type: string
     href:
      type: string
     mediaTypes:
      type: array
      items: 
       type: string
     actions:
      type: array
      items:
       type: string
       enum: 
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
    required:
      - rel
      - href
   Links:
    type: object
    properties:
      links:
        type: array
        items:
         $ref: "#/components/schemas/Link"
   ReservationReceipt:
    allOf:
     - $ref: "#/components/schemas/Links"
     - type: object
       properties:
          id:
            type: string
          expiryDate:
            type: string
          lastUpdated:
            type: string
          rooms:
            type: array
            items:
             $ref: "#/components/schemas/Reservation"
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
- [x] Unit tests 
   > Code coverage information
- [ ] Integration tests

   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 1]
```diff
@@ -60,55 +63,113 @@ public OpenAPIComponentMapper(Components components, SemanticModel semanticModel
...
         String componentName = typeSymbol.getName().orElseThrow().trim();
-        Schema componentSchema = new Schema();
-        componentSchema.setType("object");
-        Map<String, Schema> schemaProperties = new HashMap<>();
         if (typeSymbol instanceof TypeReferenceTypeSymbol) {
             TypeReferenceTypeSymbol typeRef = (TypeReferenceTypeSymbol) typeSymbol;
             // Handle record type request body
             if (typeRef.typeDescriptor() instanceof RecordTypeSymbol) {
-                //Handel typeInclusions
+                // Handel typeInclusions with allOf type binding
```
Comment (LakshanSS) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:70]: Typo:
Handel -> Handle

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIRequestBodyMapper.java [hunk 2]
```diff
@@ -1,19 +1,19 @@
 /*
- *  Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
+ * Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (LakshanSS) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIRequestBodyMapper.java:2]: No need to change the year

Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIRequestBodyMapper.java:2]: Mistakenly added 2020 as a license, Since this class is introduced in 2021.

**Review by indikasampath2000 — APPROVED** [review]
