### PR TITLE
Fix output path issue with relative path

### LINKED ISSUE #13: Can not resolve relative path in output path with openapi-cli command
**Description:**
Openpi-cli command was unable to resolve the output path when it provide as relative path
ex: `ballerina openapi -i petstore.yaml -o ../`  gave the error couldn't read the given contract file .

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by lnash94**
## Purpose
To fix the relative path problem with the output option
> fix #13 

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenAPIValidatorPlugin.java [hunk 1]
```diff
@@ -128,7 +128,11 @@ public void process(ServiceNode serviceNode, List<AnnotationAttachmentNode> anno
                                         }
                                     }
                                     if (file != null && file.exists()) {
-                                        contractURI = file.getAbsolutePath();
+                                        try {
+                                            contractURI = file.getCanonicalPath();
+                                        } catch (IOException e) {
+                                            e.printStackTrace();
```
Comment (hemikak) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenAPIValidatorPlugin.java:134]: Should this be handled like this ?
```java
 dLog.logDiagnostic(Diagnostic.Kind.ERROR, annotation.getPosition(),
                                            "Contract path should be applied as a string value");
```

File: openapi-cli/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICmdTest.java [hunk 2]
```diff
@@ -135,4 +136,18 @@ public void testSuccessfulServiceGeneration() throws IOException {
...
+    @Test(description = "getRelative path")
+    public void getRelativePath() {
+        OpenApiCmd cmd = new OpenApiCmd();
+        File resource01 = new File("dir1/test.txt");
+        String target01 = "dir1/dir2";
+        File resource02 = new File("dir1/dir2/dir3/test.txt");
+        String target02 = "dir1/dir2";
+        File resource03 = new File("dir2/dir3/dir4/test.txt");
+        String target03 = "dir/dir1";
+        Assert.assertEquals(cmd.getRelativePath(resource01, target01).toString(),"../test.txt");
```
Comment (hemikak) [inline openapi-cli/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICmdTest.java:149]: Need space before the 2nd argument.

`, "../test.txt");`

Comment (hemikak) [reply openapi-cli/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICmdTest.java:149]: Do the same for the next 2 lines.

**Review by hemikak — APPROVED** [review]

**Review by keizer619 — APPROVED** [review]
