### PR TITLE
[BallerinaToOAS] fix for handling ballerina record field has Union type for OAS schema

### LINKED ISSUE #587: Handle ballerina record field has Union type for OAS schema
**Description:**
- [x] Scenario 01 also represent the ballerina union type with `string or nil`, this not to map with oneOf in OAS

```ballerina
public type Link record {|
   string href;
   string? rel?;|}
```
```openapi
Link:
      required:
        - href
      type: object
      properties:
        rel:
          type: string
          nullable: true
        href:
          type: string
```
- [x] Scenario 02  represent the ballerina union type with `Dog` or `nil`, this will represent that type field should be `null` or `Dog` record to map with oneOf in OAS in below way

```ballerina
public type Pet record {|
   string? id?;
   Dog? type; |}
```
```openapi
Pet:
      required:
        - pet
      type: object
      properties:
        id:
          type: string
        type:
          oneOf:
            - $ref: '#/components/schemas/Dog'
          nullable: true  
```

- [x] Scenario03 record has Record type union types, This union type simply maps with oneOf in OAS.
```ballerina
public type Pet record {|
   string? id?;
   Dog|Cat type; |}
```
```openapi
Pet:
      required:
        - pet
      type: object
      properties:
        id:
          type: string
          nullable: true
        type:
          oneOf:
            - $ref: '#/components/schemas/Dog'
            - $ref: '#/components/schemas/Cat'
```

- [ ]  Scenario04 record has Record type union types, This union type simply maps with oneOf in OAS.
```ballerina
public type Pet record {|
   string? id?;
   Dog|Cat? type; |}
```
```openapi
Pet:
      required:
        - pet
      type: object
      properties:
        id:
          type: string
          nullable: true
        type:
          oneOf:
            - $ref: '#/components/schemas/Dog'
            - $ref: '#/components/schemas/Cat'
          nullable: true 
```

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests - add
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 1]
```diff
@@ -233,32 +233,49 @@ private Schema handleTypeReference(Map<String, Schema> schema, TypeReferenceType
...
                 property = ConverterCommonUtils.getOpenApiSchema(union.typeKind().getName().trim());
                 TypeReferenceTypeSymbol typeReferenceTypeSymbol = (TypeReferenceTypeSymbol) union;
-                property = handleTypeReference(schema, typeReferenceTypeSymbol, property);
-                componentName = union.getName().orElseThrow(null);
+                property = handleTypeReference(this.components.getSchemas(), typeReferenceTypeSymbol, property);
+                properties.add(property);
+                // commented due to known issue in ballerina lang union type handling
+//            } else if (union.typeKind() == TypeDescKind.UNION) {
+//                property = handleUnionType((UnionTypeSymbol) union, property, properties);
+//                properties.add(property);
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:252]: Have you created an issue for this? If so, better to add a Todo item to enable this once the fix is merged

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 2]
```diff
@@ -233,32 +233,49 @@ private Schema handleTypeReference(Map<String, Schema> schema, TypeReferenceType
...
      */
-    private Schema handleUnionType(Map<String, Schema> schema, Map.Entry<String, RecordFieldSymbol> field,
-                                   Schema property) {
-
-        List<TypeSymbol> unionTypes = ((UnionTypeSymbol) field.getValue().typeDescriptor()).userSpecifiedMemberTypes();
-        String componentName = null;
+    private Schema handleUnionType(UnionTypeSymbol unionType, Schema property) {
+        List<TypeSymbol> unionTypes = unionType.userSpecifiedMemberTypes();
+        //Set array size to 4 by assuming union type can have max 4 types.
+        List<Schema> properties = new ArrayList<>(4);
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:239]: Are there any specific reasons for this assumption?

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 3]
```diff
@@ -233,32 +233,49 @@ private Schema handleTypeReference(Map<String, Schema> schema, TypeReferenceType
...
+//                property = handleUnionType((UnionTypeSymbol) union, property, properties);
+//                properties.add(property);
             } else {
                 property = ConverterCommonUtils.getOpenApiSchema(union.typeKind().getName().trim());
+                properties.add(property);
             }
         }
+
+        property = generateOneOfSchema(property, properties);
+
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:260]: Additional blank lines?

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 4]
```diff
@@ -233,32 +233,49 @@ private Schema handleTypeReference(Map<String, Schema> schema, TypeReferenceType
...
+    }
+
+    /**
+     * This function generate oneOf composed schema for record fields.
+     */
+    private Schema generateOneOfSchema(Schema property, List<Schema> properties) {
+        boolean isTypeReference = (properties.size() == 1) && (properties.get(0).get$ref() == null);
+        if ((properties.size() == 1) && (properties.get(0).get$ref() == null)) {
+            isTypeReference = true;
+        }
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:274]: Redundant re-assignment for `isTypeReference`

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_primitive.bal [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+    int id;
+    string eat?;
+|};
+
+listener  http:Listener  ep0  = new (443, config  = {host: "petstore.swagger.io"});
+
+ service  /payloadV  on  ep0  {
+        resource  function  post  pet(@http:Payload Link payload) {
+    }
+}
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_primitive.bal:23]: Incorrect formatting (additional whitespaces).. Please re-check all newly added Ballerina test sources as I've noticed multiple places with formatting issues

File: openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RecordTests.java [hunk 6]
```diff
@@ -70,6 +70,25 @@ public void testNullableFieldWithTypeReference() throws OpenApiConverterExceptio
...
+    }
+
+    @Test(description = "When the record field has nullable field , which has record type reference data type")
+    public void testUnionTypeWithPrimitive() throws OpenApiConverterException, IOException {
+        Path ballerinaFilePath = RES_DIR.resolve("record/union_with_primitive.bal");
+        TestUtils.compareWithGeneratedFile(ballerinaFilePath, "record/union_with_primitive.yaml");
+    }
+
+    @Test(description = "When the record field has nullable field , which has record type reference data type",
+            enabled = false)
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RecordTests.java:86]: Is this disabled intentionally?

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java (hunk 1 above)
Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:252]: Yeah There is created issue, will add TODO as well

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java (hunk 2 above)
Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:239]: Since by default, it takes list array size 10, due to this avoiding the memory allocation.

File: openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RecordTests.java (hunk 6 above)
Comment (lnash94) [reply openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RecordTests.java:86]: yeah due to that ballerina lang known issue this is disabled.

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_primitive.bal (hunk 5 above)
Comment (lnash94) [reply openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_primitive.bal:23]: sure will format

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java (hunk 2 above)
Comment (NipunaRanasinghe) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:239]: I see. I was concerned since theres no compile time / runtime guarantee that a union type cannot have more than 4 nested types AFAIK

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 7]
```diff
@@ -233,32 +233,47 @@ private Schema handleTypeReference(Map<String, Schema> schema, TypeReferenceType
...
+    }
+
+    /**
+     * This function generate oneOf composed schema for record fields.
+     */
+    private Schema generateOneOfSchema(Schema property, List<Schema> properties) {
+        boolean isTypeReference = false;
+        if ((properties.size() == 1) && (properties.get(0).get$ref() == null)) {
+            isTypeReference = true;
+        }
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:272]:
```suggestion
        boolean isTypeReference = properties.size() == 1 && properties.get(0).get$ref() == null;
```

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_primitive.bal [hunk 8]
```diff
@@ -0,0 +1,24 @@
...
+    string eat?;
+|};
+
+listener http:Listener ep0 = new(443, config  = {host: "petstore.swagger.io"});
+
+ service /payloadV on ep0 {
+        resource function post pet(@http:Payload Link payload) {
+    }
+}
+
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_primitive.bal:24]: Additional blank line

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_primitive.bal [hunk 9]
```diff
@@ -0,0 +1,24 @@
...
+    int? id;
+    string name?;
+|};
+
+type Cat record {|
+    int id;
+    string eat?;
+|};
+
+listener http:Listener ep0 = new(443, config  = {host: "petstore.swagger.io"});
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_primitive.bal:18]:
```suggestion
listener http:Listener ep0 = new(443, config = {host: "petstore.swagger.io"});
```

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_primitive.bal [hunk 10]
```diff
@@ -0,0 +1,24 @@
...
+
+ service /payloadV on ep0 {
+        resource function post pet(@http:Payload Link payload) {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_primitive.bal:21]:
```suggestion
    resource function post pet(@http:Payload Link payload) {
```

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_nullable.bal [hunk 11]
```diff
@@ -0,0 +1,24 @@
...
+
+type Cat record {|
+    int id;
+    string eat?;
+|};
+
+listener  http:Listener ep0 = new(443, config  = {host: "petstore.swagger.io"});
+
+ service /payloadV on ep0 {
+        resource function post pet(@http:Payload Link payload) {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_nullable.bal:21]:
```suggestion
    resource function post pet(@http:Payload Link payload) {
```

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_nullable.bal [hunk 12]
```diff
@@ -0,0 +1,24 @@
...
+    int? id;
+    string name?;
+|};
+
+type Cat record {|
+    int id;
+    string eat?;
+|};
+
+listener  http:Listener ep0 = new(443, config  = {host: "petstore.swagger.io"});
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_nullable.bal:18]:
```suggestion
listener http:Listener ep0 = new(443, config = {host: "petstore.swagger.io"});
```

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/optional.bal [hunk 13]
```diff
@@ -12,9 +12,9 @@ type Pet record {|
     string name?;
 |};
 
-listener  http:Listener  ep0  = new (443, config  = {host: "petstore.swagger.io"});
+listener http:Listener ep0 = new(443, config  = {host: "petstore.swagger.io"});
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/ballerina-to-openapi/record/optional.bal:15]:
```suggestion
listener http:Listener ep0 = new(443, config = {host: "petstore.swagger.io"});
```

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/optional.bal [hunk 14]
```diff
@@ -12,9 +12,9 @@ type Pet record {|
...
 
- service  /payloadV  on  ep0  {
-        resource  function  post  pet(@http:Payload Link payload) {
+ service /payloadV on ep0 {
+        resource function post pet(@http:Payload Link payload) {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/ballerina-to-openapi/record/optional.bal:18]:
```suggestion
    resource function post pet(@http:Payload Link payload) {
```

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/optional.bal (hunk 13 above)
Comment (NipunaRanasinghe) [reply openapi-cli/src/test/resources/ballerina-to-openapi/record/optional.bal:15]:
```suggestion
listener http:Listener ep0 = new(443, config = {host: "petstore.swagger.io"});
```

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/nullable01.bal [hunk 15]
```diff
@@ -1,14 +1,13 @@
-import  ballerina/http;
+import ballerina/http;
 
 type Link record {|
    string? rel?;
    string href;
 |};
 
+listener http:Listener ep0 = new (443, config  = {host: "petstore.swagger.io"});
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/ballerina-to-openapi/record/nullable01.bal:8]:
```suggestion
listener http:Listener ep0 = new(443, config = {host: "petstore.swagger.io"});
```

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/union.bal [hunk 16]
```diff
@@ -0,0 +1,24 @@
...
+
+type Cat record {|
+    int id;
+    string eat?;
+|};
+
+listener http:Listener ep0 = new(443, config = {host: "petstore.swagger.io"});
+
+ service /payloadV on ep0 {
+        resource function post pet(@http:Payload Link payload) {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/ballerina-to-openapi/record/union.bal:21]:
```suggestion
    resource function post pet(@http:Payload Link payload) {
```

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/nullable01.bal [hunk 17]
```diff
@@ -1,14 +1,13 @@
...
 
-listener  http:Listener  ep0  = new (443, config  = {host: "petstore.swagger.io"});
-
- service  /payloadV  on  ep0  {
-        resource  function  post  pet(@http:Payload Link payload) {
+ service /payloadV on ep0 {
+        resource function post pet(@http:Payload Link payload) {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/ballerina-to-openapi/record/nullable01.bal:11]:
```suggestion
    resource function post pet(@http:Payload Link payload) {
```

File: openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_nullable.bal [hunk 18]
```diff
@@ -0,0 +1,24 @@
...
+
+ service /payloadV on ep0 {
+        resource function post pet(@http:Payload Link payload) {
+    }
+}
+
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_nullable.bal:24]: Additional blank line

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 19]
```diff
@@ -233,32 +233,47 @@ private Schema handleTypeReference(Map<String, Schema> schema, TypeReferenceType
...
+    }
+
+    /**
+     * This function generate oneOf composed schema for record fields.
+     */
+    private Schema generateOneOfSchema(Schema property, List<Schema> properties) {
+        boolean isTypeReference = properties.size() == 1 && properties.get(0).get$ref() == null;
+//        if ((properties.size() == 1) && (properties.get(0).get$ref() == null)) {
+//            isTypeReference = true;
+//        }
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:272]: Lets remove the commented lines

**Review by NipunaRanasinghe — COMMENTED** [review]
LGTM!

**Review by shafreenAnfar — APPROVED** [review]
