### PR TITLE
Fixed Windows tests failure 

### LINKED ISSUE #134: Tests failure in windows flow for ballerina to openapi command
**Description:**
`ballerina to openpapi` command tests fail in windows flow by giving this exceptions 

```
io.ballerina.projects.ProjectException: java.nio.charset.UnmappableCharacterException: Input length = 1	
at io.ballerina.projects.internal.ProjectFiles.loadDocument(ProjectFiles.java:152)	
•••
at org.ballerinalang.ballerina.OpenApiConverterUtils.generateOAS3DefinitionsAllService(OpenApiConverterUtils.java:122)	
at org.ballerinalang.ballerina.OpenApiConverterUtilsTest.testXmlPayLoad(OpenApiConverterUtilsTest.java:126)	
••• 
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICmdTest.java [hunk 1]
```diff
@@ -122,7 +122,7 @@ public void testSuccessfulServiceGeneration() throws IOException {
         }
     }
 
-    @Test(description = "Test ballerina to openapi", enabled = false)
+    @Test(description = "Test ballerina to openapi", enabled = true)
```
Comment (hemikak) [inline openapi-cli/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICmdTest.java:125]: Can we remove the `enabled` attribute itself ?

**Review by hemikak — APPROVED** [review]
