### PR TITLE
Fix add exit code for openAPI command

### LINKED ISSUE #136: `openapi` command doesn't work when a .yml file is provided
I tried to run the command as follows:
```
$ bal openapi -i petstore.yml
Note: This is an experimental tool, which only supports a limited set of functionality.
error: An OpenApi definition file is required to generate the service.
E.g: ballerina openapi --input <OpenApiContract> or <Ballerina file>
```
Shouldn't it accept `.yml` files as well?

### LINKED ISSUE #171: Add exit codes to the OpenAPI commands
**Description:**

$subject

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by lnash94**
Fix #171 

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaSchemaGenerator.java [hunk 1]
```diff
@@ -315,7 +315,7 @@ public static OpenAPI parseOpenAPIFile(String definitionURI) throws OpenApiExcep
         if (!Files.exists(contractPath)) {
```
Comment (pramodya1994) [inline openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaSchemaGenerator.java:315]: Shall we refactor `parseOpenAPIFile` a bit?
- Access can be private
- `parseResult.getMessages().size() > 0` can be replaced with `!parseResult.getMessages().isEmpty()`
- `api` variable seems redundant, can immediately return `return parseResult.getOpenAPI()`

File: openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java [hunk 2]
```diff
@@ -130,21 +133,28 @@ public void execute() {
                 Filter filter = new Filter(tag, operation);
                 try {
                     openApiToBallerina(fileName, filter);
+                    exitWithCode(0);
+                    return;
```
Comment (pramodya1994) [inline openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java:137]: Seems these last 4 returns this one and the rest seems not needed in this void method. You can safely remove those.

File: openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java [hunk 3]
```diff
@@ -245,9 +253,13 @@ private void generatesClientFile(CodeGenerator generator, String clientName, Pat
                     targetOutputPath.toString(), filter);
         } catch (IOException | BallerinaOpenApiException | FormatterException | OpenApiException e) {
             if (e.getLocalizedMessage() != null) {
-                throw LauncherUtils.createLauncherException(e.getLocalizedMessage());
+                outStream.println(e.getLocalizedMessage());
+                exitWithCode(1);
+                return;
```
Comment (pramodya1994) [inline openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java:258]: `return;` can be safely removed

File: openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java [hunk 4]
```diff
@@ -245,9 +253,13 @@ private void generatesClientFile(CodeGenerator generator, String clientName, Pat
...
             } else {
-                throw LauncherUtils.createLauncherException(OpenApiMesseges.OPENAPI_CLIENT_EXCEPTION);
+                outStream.println(OpenApiMesseges.OPENAPI_CLIENT_EXCEPTION);
+                exitWithCode(1);
+                return;
```
Comment (pramodya1994) [inline openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java:262]: here too.

Comment (pramodya1994) [reply openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java:262]: L 284, 305 returns also can be removed

File: openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java [hunk 5]
```diff
@@ -306,4 +322,8 @@ public void printUsage(StringBuilder stringBuilder) {
     @Override
     public void setParentCmdParser(CommandLine parentCmdParser) {
     }
+
+    public void exitWithCode(int exit) {
```
Comment (pramodya1994) [inline openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java:326]: can be private

File: openapi-cli/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICmdTest.java [hunk 6]
```diff
@@ -122,6 +122,49 @@ public void testSuccessfulServiceGeneration() throws IOException {
...
     }
 
+    @Test(description = "Test openapi gen-service for successful service generation")
+    public void testSuccessfulServiceGenerationForYML() throws IOException {
+        Path petstoreYaml = resourceDir.resolve(Paths.get("petstore.yml"));
+        String[] args = {"--input", petstoreYaml.toString(), "-o", this.tmpDir.toString()};
+        OpenApiCmd cmd = new OpenApiCmd(printStream, tmpDir);
+        new CommandLine(cmd).parseArgs(args);
+
+        String output = "";
```
Comment (pramodya1994) [inline openapi-cli/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICmdTest.java:132]: `output` is assigned, but not used anywhere

**Review by pramodya1994 — CHANGES_REQUESTED** [review]
@lnash94 Added few comments

File: openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java [hunk 7]
```diff
@@ -92,33 +93,43 @@
     public OpenApiCmd() {
         this.outStream = System.err;
         this.executionPath = Paths.get(System.getProperty("user.dir"));
+        this.exitWhenFinish = true;
     }
 
     public OpenApiCmd(PrintStream outStream, Path executionDir) {
         this.outStream = outStream;
         this.executionPath = executionDir;
+        this.exitWhenFinish = true;
```
Comment (hemikak) [inline openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java:102]: These 2 constructors can be changed to call the `public OpenApiCmd(PrintStream outStream, Path executionDir, boolean exitWhenFinish)` constructor rather than assigning to each class field.

**Comment by hemikak** [comment]
Have we checked if the exit code is coming correctly by manual testing ? Refer: https://www.cyberciti.biz/faq/bash-get-exit-code-of-command/

File: openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java [hunk 8]
```diff
@@ -92,33 +93,43 @@
...
             return;
         }
         //Check if cli input argument is present
         if (inputPath) {
             //Check if an OpenApi definition is provided
             if (argList == null) {
-                throw LauncherUtils.createLauncherException(OpenApiMesseges.MESSAGE_FOR_MISSING_INPUT);
+                outStream.println(OpenApiMesseges.MESSAGE_FOR_MISSING_INPUT);
+                exitError(this.exitWhenFinish);
+                return;
```
Comment (hemikak) [inline openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java:126]: Check if this `return` is needed.

Comment (lnash94) [reply openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java:122]: This return needs to terminate the command in the test cases

**Review by hemikak — APPROVED** [review]

**Review by pramodya1994 — APPROVED** [review]
