### PR TITLE
Fix for enabling the OpenAPI Validator Plugin

### LINKED ISSUE #82: Enable OpenAPI Validator Plugin
**Description:**
Refactor openapi validator plugin

- [x] Extract annotation details for validation, To match consider the tags and operations provided with the annotation.

>Match available the openapi contract operation with the functions of the resource
Match available resources with the openapi contract operation

- [x] Implement a model for getting a summary of all the openapi contract path with paths' available methods and parameters.
- [x] Implement a model for getting a summary of all the resource function path with paths' available methods and parameters.
- [x] If the resource is missing service will be highlighted with the missing resource error 
- [ ] If there is an extra resource in service the resource will be highlighted with an error
>Implement the Service validator (with filtered operations)
- [x] Resource function node validates against the operation model
- [x] Operation model validate against the resource function node

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-tests/src/test/java/org/ballerinalang/openapi/validator/tests/BaseTests.java [hunk 1]
```diff
@@ -0,0 +1,182 @@
+/*
+ * Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (pramodya1994) [inline openapi-tests/src/test/java/org/ballerinalang/openapi/validator/tests/BaseTests.java:2]:
```suggestion
 * Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```

File: openapi-tests/src/test/java/org/ballerinalang/openapi/validator/tests/BaseTests.java [hunk 2]
```diff
@@ -0,0 +1,182 @@
...
+import io.swagger.v3.oas.models.media.Schema;
+import org.testng.Assert;
+
+import java.nio.file.Path;
+import java.nio.file.Paths;
+import java.util.Iterator;
+import java.util.Optional;
+
+/**
+ * This BaseTests class use for main initializing of the tests.
```
Comment (pramodya1994) [inline openapi-tests/src/test/java/org/ballerinalang/openapi/validator/tests/BaseTests.java:60]: Should we add `@since`?

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ErrorMessages.java [hunk 3]
```diff
@@ -22,100 +22,159 @@
  */
 class ErrorMessages {
 
-    static String invalidFilePath(String path) {
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ErrorMessages.java:25]: Seems like there are some unused methods in this class, If we don't need them we can remove.

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceMethod.java [hunk 4]
```diff
@@ -57,46 +65,20 @@ public void setMethod(String method) {
...
+    public void setBody(Boolean body) {
         this.body = body;
     }
 
     public void setResourcePosition(Location position) {
         this.resourcePosition = position;
     }
 
-    public Location getResourcePosition() {
+    public Location getResourcePosition(NodeLocation location) {
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceMethod.java:81]: `location` is never used

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceValidator.java [hunk 5]
```diff
@@ -197,46 +245,80 @@ private static Boolean validateRequestBodyResourceToOpenApi(Operation operation,
...
+            typeSymbol = symbolVar.typeDescriptor();
+        } else if (symbol.isPresent() && symbol.orElseThrow().kind().equals(SymbolKind.PARAMETER)) {
+            ParameterSymbol symbolParam = (ParameterSymbol) symbol.orElseThrow();
+            typeSymbol = symbolParam.typeDescriptor();
+        }
+
+        return typeSymbol;
+    }
+
+    public static Map<String, Schema> getRequestBodyForOperation(Operation operation) {
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceValidator.java:272]: Access can be private

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceWithOperation.java [hunk 6]
```diff
@@ -192,241 +193,164 @@
...
+            while (pathNodeIter.hasNext()) {
+                Node next = pathNodeIter.next();
+                String node = next.toString().trim();
+                if (next instanceof ResourcePathParameterNode) {
+                    ResourcePathParameterNode pathParameterNode = (ResourcePathParameterNode) next;
+                    String paramName = pathParameterNode.paramName().text();
+                    node = "{" + paramName + "}";
+                    parameterNodeMap.put(paramName, next);
                 }
+                functionPath = functionPath + node;
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceWithOperation.java:301]: Shall we use `StringBuilder` and `append()`?

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceWithOperation.java [hunk 7]
```diff
@@ -192,241 +193,164 @@
...
+            }
+            if (resourceSummaryList.containsKey(functionPath)) {
+                setParametersToMethod(functionDefinitionNode, functionMethod, parameterNodeMap,
+                        resourceSummaryList.get(functionPath));
+            } else {
+                ResourcePathSummary resourcePathSummary = new ResourcePathSummary();
+                //Set location as first function loacation
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceWithOperation.java:308]:
```suggestion
                // Set location as first function location
```

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceWithOperation.java [hunk 8]
```diff
@@ -192,241 +193,164 @@
...
+        resourcePathSummary2.addMethod(functionMethod, resourceMethod);
     }
 
     /**
      * Summarize openAPI contract paths to easily access details to validate.
      * @param contract                openAPI contract
      * @return List of summarized OpenAPIPathSummary
      */
-    public static List<OpenAPIPathSummary>   summarizeOpenAPI(OpenAPI contract) {
+    public static List<OpenAPIPathSummary> summarizeOpenAPI(OpenAPI contract) {
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceWithOperation.java:353]: Can be private

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java [hunk 9]
```diff
@@ -1,180 +1,293 @@
...
-                }
+    @Override
+    public void perform(SyntaxNodeAnalysisContext syntaxNodeAnalysisContext) {
+        List<FunctionDefinitionNode> functions = new ArrayList<>();
+        DiagnosticSeverity kind = DiagnosticSeverity.ERROR;
+        Filters filters = new Filters(kind);
+        SemanticModel semanticModel = syntaxNodeAnalysisContext.semanticModel();
+        SyntaxTree syntaxTree = syntaxNodeAnalysisContext.syntaxTree();
+
+        //Generate ballerina file path
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java:87]:
```suggestion
        // Generate ballerina file path
```

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java [hunk 10]
```diff
@@ -1,180 +1,293 @@
...
+                    Optional<MappingConstructorExpressionNode> mappingConstructorExpressionNode =
+                            annotationNode.annotValue();
+                    MappingConstructorExpressionNode exprNode = mappingConstructorExpressionNode.orElseThrow();
+                    SeparatedNodeList<MappingFieldNode> fields = exprNode.fields();
+                    //Filter annotation attributes
+                    if (!fields.isEmpty()) {
+                        try {
+                            kind = extractOpenAPIAnnotation(kind, filters, annotationNode, ballerinaFilePath);
+                        } catch (IOException e) {
+                            DiagnosticInfo diagnosticInfo = new DiagnosticInfo("BAL_OPENAPI_VALIDATOR_0019",
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java:135]: Shall we use a constant for `"BAL_OPENAPI_VALIDATOR_0019"`?

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java [hunk 11]
```diff
@@ -186,18 +299,101 @@ public static void validateResource(OpenAPI openApi,
         }
     }
 
+    //Extract details from openapi annotation.
+    public static DiagnosticSeverity extractOpenAPIAnnotation(DiagnosticSeverity kind, Filters filters,
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java:303]: Can this method be private?

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java [hunk 12]
```diff
@@ -186,18 +299,101 @@ public static void validateResource(OpenAPI openApi,
...
+            throws IOException {
+        SeparatedNodeList<MappingFieldNode> fields = annotationNode.annotValue().orElseThrow().fields();
+        for (MappingFieldNode fieldNode: fields) {
+            if (fieldNode instanceof SpecificFieldNode) {
+                SpecificFieldNode specificFieldNode = (SpecificFieldNode) fieldNode;
+                Optional<ExpressionNode> expressionNode = specificFieldNode.valueExpr();
+                //Handle openapi contract path if path is empty return exceptions.
+                ExpressionNode openAPIAnnotation = expressionNode.orElseThrow();
+                if (specificFieldNode.fieldName().toString().trim().equals("contract")) {
+                    Path sourceRoot = ballerinaFilePath;
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java:314]: This variable is redundant

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java [hunk 13]
```diff
@@ -186,18 +299,101 @@ public static void validateResource(OpenAPI openApi,
...
+                        case "tags":
+                            List<String> tags = setFilters(list);
+                            filters.setTag(tags);
+                            break;
+                        case "excludeTags":
+                            List<String> eTags = setFilters(list);
+                            filters.setExcludeTag(eTags);
+                            break;
+                        case "operatoins":
+                        case "excludeOperations":
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java:362]: Why don't we consider these switch cases as default case?

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java [hunk 14]
```diff
@@ -186,18 +299,101 @@ public static void validateResource(OpenAPI openApi,
...
+                                             Map<String, ResourcePathSummary> resourcePathSummaryList) {
 
-        Iterator<ResourcePathSummary> resourcePathSummaryIterator = resourcePathSummaryList.iterator();
+        Iterator<Map.Entry<String, ResourcePathSummary>> resourcePathSummaryIterator = resourcePathSummaryList
+                .entrySet().iterator();
         while (resourcePathSummaryIterator.hasNext()) {
             boolean isExit = false;
-            ResourcePathSummary resourcePathSummary = resourcePathSummaryIterator.next();
+            ResourcePathSummary resourcePathSummary = resourcePathSummaryIterator.next().getValue();
             for (OpenAPIPathSummary apiPathSummary: openAPIPathSummaries) {
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java:397]: This for loop doesn't seem like iterating

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java [hunk 15]
```diff
@@ -257,47 +454,58 @@ private static void createListResourcePathSummary(List<ResourceValidationError>
...
+                    DiagnosticInfo diagnosticInfo = new DiagnosticInfo(error[0], error[1], kind);
+                    Diagnostic diagnostic = DiagnosticFactory.createDiagnostic(diagnosticInfo,
+                                    ((MissingFieldInJsonSchema) postErr).getLocation());
+                    validations.add(diagnostic);
+
                 } else if (postErr instanceof OneOfTypeValidation) {
                     if (!(((OneOfTypeValidation) postErr).getBlockErrors()).isEmpty()) {
-                        List<ValidationError> oneOferrorlist =
-                                ((OneOfTypeValidation) postErr).getBlockErrors();
+                        List<ValidationError> oneOferrorlist = ((OneOfTypeValidation) postErr).getBlockErrors();
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java:485]:
```suggestion
                        List<ValidationError> oneOfErrorList = ((OneOfTypeValidation) postErr).getBlockErrors();
```
Shouldn't we follow java naming conventions?

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java [hunk 16]
```diff
@@ -257,47 +454,58 @@ private static void createListResourcePathSummary(List<ResourceValidationError>
...
+
+                    String[] error =
                             ErrorMessages.undocumentedFieldInRecordParam(postErr.getFieldName(),
                                     ((MissingFieldInJsonSchema) postErr).getRecordName(),
-                                    method.getKey(), resourcePathSummary.getPath()));
+                                    method.getKey(), resourcePathSummary.getPath());
+                    DiagnosticInfo diagnosticInfo = new DiagnosticInfo(error[0], error[1], kind);
+                    Diagnostic diagnostic = DiagnosticFactory.createDiagnostic(diagnosticInfo,
+                                    ((MissingFieldInJsonSchema) postErr).getLocation());
+                    validations.add(diagnostic);
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java:481]: Cant we extract a method, to avoid duplocates?
```java
private static void extractMethod(DiagnosticSeverity kind, ResourcePathSummary resourcePathSummary,
            Map.Entry<String, ResourceMethod> method, ValidationError postErr) {
        String[] error = ErrorMessages.undocumentedFieldInRecordParam(postErr.getFieldName(),
                                                                      ((MissingFieldInJsonSchema) postErr)
                                                                              .getRecordName(), method.getKey(),
                                                                      resourcePathSummary.getPath());
        DiagnosticInfo diagnosticInfo = new DiagnosticInfo(error[0], error[1], kind);
        Diagnostic diagnostic = DiagnosticFactory
                .createDiagnostic(diagnosticInfo, ((MissingFieldInJsonSchema) postErr).getLocation());
        validations.add(diagnostic);
    }
    ```

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java [hunk 17]
```diff
@@ -345,22 +557,26 @@ private static void generateTypeMisMatchDlog(DiagnosticSeverity kind, Diagnostic
...
      */
-    public static OpenAPI parseOpenAPIFile(String definitionURI) throws OpenApiValidatorException {
+    public static OpenAPI parseOpenAPIFile(String definitionURI) throws OpenApiValidatorException, IOException {
         Path contractPath = Paths.get(definitionURI);
         ParseOptions parseOptions = new ParseOptions();
         parseOptions.setResolve(true);
         parseOptions.setResolveFully(true);
-        parseOptions.setFlatten(true);
+        // Enable this if you need to create new schema from references
+        //parseOptions.setFlatten(true);
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java:566]: Shall we remove these lines?

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/TypeSymbolToJsonValidatorUtil.java [hunk 18]
```diff
@@ -0,0 +1,438 @@
...
+    public static List<ValidationError> validate(Schema<?> schema, TypeSymbol typeSymbol,
+                                                 SyntaxTree syntaxTree, SemanticModel semanticModel,
+                                                 String componentName, Location location)
+            throws OpenApiValidatorException {
+        String paramName = "";
+        String schemaType = "";
+        String ballerinaType = "";
+        List<ValidationError> validationErrorList = new ArrayList<>();
+        boolean isExitType = false;
+        //Check given type is record or not
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/TypeSymbolToJsonValidatorUtil.java:65]:
```suggestion
        // Check given type is a record or not
```

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/TypeSymbolToJsonValidatorUtil.java [hunk 19]
```diff
@@ -0,0 +1,438 @@
...
+            if (((ArrayTypeSymbol) typeSymbol).memberTypeDescriptor().typeKind().getName().toLowerCase(Locale.ENGLISH)
+                    .equals(convertOpenAPITypeToBallerina(((ArraySchema) schema).getItems().getType()))) {
+                isExitType = true;
+            } else if ((((ArraySchema) schema).getItems() instanceof ObjectSchema) &&
+                    (((ArrayTypeSymbol) typeSymbol).memberTypeDescriptor() instanceof TypeReferenceTypeSymbol)) {
+                TypeSymbol recordType = null;
+                isExitType = true;
+                Optional<TypeSymbol> symbol = semanticModel
+                        .type(((ArrayTypeSymbol) typeSymbol).memberTypeDescriptor().location().lineRange());
+                if (symbol != null && symbol.isPresent()) {
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/TypeSymbolToJsonValidatorUtil.java:108]: Do we need this null check for optional?

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/TypeSymbolToJsonValidatorUtil.java [hunk 20]
```diff
@@ -0,0 +1,438 @@
...
+                List<ValidationError> recordValidationError = validate(((ArraySchema) schema).getItems(),
+                        recordType, syntaxTree, semanticModel, componentName, location);
+                validationErrorList.addAll(recordValidationError);
+
+            } else if ((((ArraySchema) schema).getItems() instanceof ArraySchema) &&
+                    (((ArrayTypeSymbol) typeSymbol).memberTypeDescriptor() instanceof ArrayTypeSymbol)) {
+                // handle nested array
+                isExitType = true;
+                ArrayTypeSymbol traverseNestedArray = (ArrayTypeSymbol) typeSymbol;
+                ArraySchema traversSchemaNestedArray = (ArraySchema) schema;
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/TypeSymbolToJsonValidatorUtil.java:120]: Assignments are overriding inside if & these variables not used in the else part, So these assignments seem not needed.

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/TypeSymbolToJsonValidatorUtil.java [hunk 21]
```diff
@@ -0,0 +1,438 @@
...
+                    }
+                }
+                if (!error.isEmpty()) {
+                    validationErrorList.addAll(error);
+                }
+            }
+        }
+
+        if (!isExitType) {
+            assert schema != null;
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/TypeSymbolToJsonValidatorUtil.java:170]: Shall we replace this with a if else?

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/TypeSymbolToJsonValidatorUtil.java [hunk 22]
```diff
@@ -0,0 +1,438 @@
...
+                        convertTypeToEnum(entry.getValue().getType()), componentName);
+                validationErrorList.add(validationError);
+            }
+        }
+        return validationErrorList;
+    }
+
+    private static void validateArrayType(List<ValidationError> validationErrorList, RecordFieldSymbol fieldSymbol,
+                                      Map.Entry<String, Schema> entry, SyntaxTree syntaxTree,
+                                          SemanticModel semanticModel, String componetName, Location location)
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/TypeSymbolToJsonValidatorUtil.java:264]:
```suggestion
                                          SemanticModel semanticModel, String componentName, Location location)
```

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/TypeSymbolToJsonValidatorUtil.java [hunk 23]
```diff
@@ -0,0 +1,438 @@
...
+        }
+        return convertedType;
+    }
+
+    /**
+     * Method for convert openApi type to ballerina type.
+     * @param type  OpenApi parameter types
+     * @return ballerina type
+     */
+    public static String convertOpenAPITypeToBallerina(String type) {
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/TypeSymbolToJsonValidatorUtil.java:372]:
```suggestion
    private static String convertOpenAPITypeToBallerina(String type) {
```

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/diagnostics/OpenAPIDiagnostics.java [hunk 24]
```diff
@@ -0,0 +1,65 @@
...
+import io.ballerina.tools.diagnostics.DiagnosticInfo;
+import io.ballerina.tools.diagnostics.DiagnosticProperty;
+import io.ballerina.tools.diagnostics.Location;
+
+import java.util.List;
+
+/**
+ * This util class use for creating OpenAPI diagnostic.
+ */
+public class OpenAPIDiagnostics extends Diagnostic {
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/diagnostics/OpenAPIDiagnostics.java:31]: Seems this class hasn't used anywhere.

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/error/MissingFieldInJsonSchema.java [hunk 25]
```diff
@@ -28,17 +29,29 @@
     String fieldName;
     Constants.Type type;
     String recordName;
+    Location location;
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/error/MissingFieldInJsonSchema.java:32]: Shall we make these private?

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/error/TypeMismatch.java [hunk 26]
```diff
@@ -27,21 +28,33 @@
 public class TypeMismatch extends ValidationError {
     String recordName;
     String fieldName;
+    Location location;
     Constants.Type typeJsonSchema;
     Constants.Type typeBallerinaType;
```
Comment (pramodya1994) [inline openapi-validator/src/main/java/org/ballerinalang/openapi/validator/error/TypeMismatch.java:33]: Shall we make these private?

File: openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/BaseTests.java [hunk 27]
```diff
@@ -0,0 +1,182 @@
...
+
+import java.nio.file.Path;
+import java.nio.file.Paths;
+import java.util.Iterator;
+import java.util.Optional;
+
+/**
+ * This BaseTests class use for main initializing of the tests.
+ */
+public class BaseTests {
```
Comment (pramodya1994) [inline openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/BaseTests.java:62]: Do we have any usages of this?

File: openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/OpenApiFilterTests.java [hunk 28]
```diff
@@ -45,65 +46,65 @@
...
+        openAPIPathSummaries = ResourceWithOperation.filterOpenapi(api, filter);
         Assert.assertEquals(openAPIPathSummaries.size(), 3);
         Assert.assertEquals(openAPIPathSummaries.get(0).getPath(), "/pets");
         Assert.assertEquals(openAPIPathSummaries.get(0).getOperations().get("get").getOperationId(), "listPets");
         excludeOperations.clear();
     }
 
     @Test(description = "When tag and operation filter enable")
-    public void testOperationswithTag() throws OpenApiValidatorException {
+    public void testOperationswithTag() throws OpenApiValidatorException, IOException {
```
Comment (pramodya1994) [inline openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/OpenApiFilterTests.java:99]: Some methods not using java method naming conventions

File: openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ResourceToOperationTests.java [hunk 29]
```diff
@@ -0,0 +1,182 @@
...
+    private OpenAPI api;
+    private Project project;
+    private Operation operation;
+    private ResourceMethod resourceMethod;
+    private SyntaxTree syntaxTree;
+    private SemanticModel semanticModel;
+    private List<ValidationError> validationError = new ArrayList<>();
+    private DiagnosticSeverity kind;
+    private DiagnosticLog dLog;
+    private Filters filters;
```
Comment (pramodya1994) [inline openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ResourceToOperationTests.java:61]: no usages

File: openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ResourceToOperationTests.java [hunk 30]
```diff
@@ -0,0 +1,182 @@
...
+        semanticModel = ValidatorTest.getSemanticModel(project);
+        validationError = ResourceValidator.validateResourceAgainstOperation(operation, resourceMethod, semanticModel
+                , syntaxTree);
+        Assert.assertTrue(validationError.get(0) instanceof TypeMismatch);
+        Assert.assertEquals(validationError.get(0).getFieldName(), "petId");
+        Assert.assertEquals(((TypeMismatch) (validationError).get(0)).getTypeJsonSchema(), Constants.Type.STRING);
+        Assert.assertEquals(((TypeMismatch) (validationError).get(0)).getTypeBallerinaType(), Constants.Type.INT);
+    }
+//    'int', 'string', 'float', 'boolean', 'decimal'
+    //Query param -
```
Comment (pramodya1994) [inline openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ResourceToOperationTests.java:128]: Format error, Also shall we add those comments to the description if we need them?

File: openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ServiceValidationTests.java [hunk 31]
```diff
@@ -15,145 +15,211 @@
...
 public class ServiceValidationTests {
-    private static final Path RES_DIR = Paths.get("src/test/resources/project-based-tests/src/serviceValidator/")
+    private static final Path RES_DIR = Paths.get("src/test/resources/project-based-tests/modules/serviceValidator/")
             .toAbsolutePath();
     private OpenAPI api;
-    private BLangPackage bLangPackage;
-    private BLangService extractBLangservice;
+    private Project project;
+    private SyntaxTree syntaxTree;
+    private ServiceDeclarationNode serviceDeclarationNode;
```
Comment (pramodya1994) [inline openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ServiceValidationTests.java:59]: some variables never used

File: openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ServiceValidationTests.java [hunk 32]
```diff
@@ -15,145 +15,211 @@
...
-//        dLog = ValidatorTest.getDiagnostic("serviceValidator/ballerina/valid/petstore.bal");
-        filters = new Filters(tag, excludeTag, operation, excludeOperation, kind);
-//        ServiceValidator.validateResource(api, extractBLangservice, filters, kind, dLog);
+        // Make resourcePath summary
+        Map<String, ResourcePathSummary> resourcePathMap = ResourceWithOperation.summarizeResources(functions);
+        //  Filter openApi operation according to given filters
+        List<OpenAPIPathSummary> openAPIPathSummaries = ResourceWithOperation.filterOpenapi(api, filters);
+        List<OpenapiServiceValidationError> openApiMissingServiceMethod =
+                ResourceWithOperation.checkOperationsHasFunctions(openAPIPathSummaries, resourcePathMap);
+        Assert.assertTrue(!openApiMissingServiceMethod.isEmpty());
```
Comment (pramodya1994) [inline openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ServiceValidationTests.java:81]:
```suggestion
        Assert.assertFalse(openApiMissingServiceMethod.isEmpty());
```

File: openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ServiceValidationTests.java [hunk 33]
```diff
@@ -15,145 +15,211 @@
...
+        Assert.assertTrue(error.get(0) instanceof TypeMismatch);
+        Assert.assertEquals(error.get(0).getFieldName(), "petId");
+        Assert.assertEquals(((TypeMismatch) error.get(0)).getTypeBallerinaType(), Constants.Type.INT);
+        Assert.assertEquals(((TypeMismatch) error.get(0)).getTypeJsonSchema(), Constants.Type.STRING);
+    }
+
+    @Test(description = "test for all the Path , Query, Payload scenarios", enabled = false)
+    public void testRecordTypeMismatch() throws OpenApiValidatorException, IOException {
+        project = ValidatorTest.getProject(RES_DIR.resolve("ballerina/invalid/all_petstore.bal"));
+//        diagnostics = ServiceValidator.validateResourceFunctions(project);
```
Comment (pramodya1994) [inline openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ServiceValidationTests.java:164]: shall we remove this?

File: openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ServiceValidationTests.java [hunk 34]
```diff
@@ -15,145 +15,211 @@
...
+                        ValidatorTest.getSemanticModel(project), ValidatorTest.getSyntaxTree(project));
+        Assert.assertTrue(!error.isEmpty());
+        Assert.assertTrue(error.get(0) instanceof TypeMismatch);
+        Assert.assertEquals(error.get(0).getFieldName(), "petId");
+        Assert.assertEquals(((TypeMismatch) error.get(0)).getTypeBallerinaType(), Constants.Type.INT);
+        Assert.assertEquals(((TypeMismatch) error.get(0)).getTypeJsonSchema(), Constants.Type.STRING);
+    }
+
+    @Test(description = "test for all the Path , Query, Payload scenarios", enabled = false)
+    public void testRecordTypeMismatch() throws OpenApiValidatorException, IOException {
```
Comment (pramodya1994) [inline openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ServiceValidationTests.java:162]: exceptions never thrown in this method

**Review by pramodya1994 — CHANGES_REQUESTED** [review]
Pls check comments

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java (hunk 13 above)
Comment (lnash94) [reply openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java:362]: yeah, we can set this as the default case.

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java (hunk 14 above)
Comment (lnash94) [reply openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java:397]: Currently, we hold iterate here due to update the undocumented path in OpenAPI spec. will continue iterate with the next implementation for the undocumented ballerina resource path.

File: openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ErrorMessages.java (hunk 3 above)
Comment (lnash94) [reply openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ErrorMessages.java:25]: We hope to use that error messages in the future implementations

**Review by hevayo — APPROVED** [review]

**Review by pramodya1994 — APPROVED** [review]
