### PR TITLE
[Service]  Add test for hyphens escaped for generated resource function names

### LINKED ISSUE #395: Give ballerina parser issue when the relative path has special character in service generation
**Description:**
When the given swagger path has some special character. It won't escape by tool while generating the relative path in resource function.
example of openapi:
```openapi
paths:
  /v3/covid-19/all:
```
generated ballerina code 
```ballerina
resource  function  get  v3/covid-19/all(string?  yesterday, string?  twoDaysAgo, string?  allowNull)  returns  CovidAll {
    }
```
solution 
```ballerina
resource  function  get  v3/covid\-19/all(string?  yesterday, string?  twoDaysAgo, string?  allowNull)  returns  CovidAll {
    }
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ParameterGeneratorTest.java [hunk 1]
```diff
@@ -51,6 +51,15 @@ public void generateService() throws IOException, BallerinaOpenApiException, For
         CommonTestFunctions.compareGeneratedSyntaxTreewithExpectedSyntaxTree("service_gen.bal", syntaxTree);
     }
 
+    @Test(description = "Generate service with path has special characters")
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ParameterGeneratorTest.java:54]:
```suggestion
    @Test(description = "Generate service with path having special characters")
```

**Review by NipunaRanasinghe — APPROVED** [review]
Approved with a minor suggestion
