### PR TITLE
[BallerinaToOAS] Fix Nullable record field mapping to OAS schema properties

### LINKED ISSUE #583: Add nullable record field mapping to OAS schema properties
**Description:**
if some record field has `string? id?`  it will enable nullable feature in related property in OAS schema
```ballerina
public type Room record {|
   # Unique identification
   string? id?;
   # Number of people that can be accommodate
   int capacity?;
   # Availability of wifi
   boolean wifi; |}
```
```openapi
Room:
     type: object
     properties:
       id:
         type: string
         description: Unique identification
         nullable: true 
       capacity:
         type: integer
         description: Number of people that can be accommodate
         format: int32
       wifi:
         type: boolean
         description: Availability of wifi
     description: Represents resort room
```
**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests  - add
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 1]
```diff
@@ -178,20 +178,13 @@ private ObjectSchema generateObjectSchemaFromRecordFields(Map<String, Schema> sc
             }
             String type = field.getValue().typeDescriptor().typeKind().toString().toLowerCase(Locale.ENGLISH);
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:179]: unused variable `type`

**Review by shafreenAnfar — APPROVED** [review]

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 2]
```diff
@@ -217,6 +210,61 @@ private ObjectSchema generateObjectSchemaFromRecordFields(Map<String, Schema> sc
...
+            EnumSymbol enumSymbol = (EnumSymbol) typeRefEnum.definition();
+            property = mapEnumValues(enumSymbol);
+        } else {
+            property.set$ref(typeReferenceSymbol.getName().orElseThrow().trim());
+            TypeSymbol recordVariable = typeReferenceSymbol;
+            TypeReferenceTypeSymbol typeRecord = (TypeReferenceTypeSymbol) recordVariable;
+            createComponentSchema(schema, typeRecord);
+        }
+        return property;
+    }
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:229]: Shall we change the method to accept an instance of `TypeReferenceTypeSymbol`, to avoid all the redundant type castings?

**Comment by shafreenAnfar** [comment]
Went through the test-cases. LGTM!

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java (hunk 1 above)
Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:179]: This `type` used for getting schema in `getOpenApiSchema()` method.

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java (hunk 2 above)
Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java]: Fix  91753a9

**Review by NipunaRanasinghe — COMMENTED** [review]
LGTM!
