### PR TITLE
Fix improve tests for ballerina-to-openapi cli command

### LINKED ISSUE #62: Improve Ballerina to OpenAPI tests
**Description:**
Tests in https://github.com/ballerina-platform/ballerina-openapi/blob/master/openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java need to improve as currently it is only checking whether the generated files are there. This is not sufficient. We need to check if the generated content is correct as well.

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java [hunk 1]
```diff
@@ -165,12 +162,46 @@ public void testRecordFieldPayLoad() throws IOException, OpenApiConverterExcepti
...
-    public void testMIMERecordFiledPayLoad() throws IOException, OpenApiConverterException {
+    public void testMIMERecordFiledPayLoad() throws OpenApiConverterException {
         Path ballerinaFilePath = RES_DIR.resolve("mime_with_recordpayload_service.bal");
-        OpenApiConverterUtils.generateOAS3DefinitionsAllService(ballerinaFilePath, this.tempDir, Optional.empty());
-        Assert.assertTrue(Files.exists(this.tempDir.resolve("payloadV-openapi.yaml")));
+        compareWithGeneratedFile(ballerinaFilePath, "mime_with_record_payload.yaml");
+    }
+
+    private String getStringFromGivenBalFile(Path expectedServiceFile, String s) throws IOException {
+
```
Comment (hemikak) [inline openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java:171]: Remove this unnecessary line

File: openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java [hunk 2]
```diff
@@ -165,12 +162,46 @@ public void testRecordFieldPayLoad() throws IOException, OpenApiConverterExcepti
...
+    private void deleteGeneratedFiles(String filename) {
+        try {
+            Files.deleteIfExists(this.tempDir.resolve(filename));
+            Files.deleteIfExists(this.tempDir.resolve("schema.bal"));
+        } catch (IOException e) {
+            //Ignore the exception
+        }
     }
+    private void compareWithGeneratedFile(Path ballerinaFilePath, String yamlFile) throws OpenApiConverterException {
```
Comment (hemikak) [inline openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java:186]: Leave empty line after previous function

File: openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java [hunk 3]
```diff
@@ -165,12 +162,46 @@ public void testRecordFieldPayLoad() throws IOException, OpenApiConverterExcepti
...
     @Test(description = "Generate OpenAPI spec for build project")
-    public void testMIMERecordFiledPayLoad() throws IOException, OpenApiConverterException {
+    public void testMIMERecordFiledPayLoad() throws OpenApiConverterException {
         Path ballerinaFilePath = RES_DIR.resolve("mime_with_recordpayload_service.bal");
-        OpenApiConverterUtils.generateOAS3DefinitionsAllService(ballerinaFilePath, this.tempDir, Optional.empty());
-        Assert.assertTrue(Files.exists(this.tempDir.resolve("payloadV-openapi.yaml")));
+        compareWithGeneratedFile(ballerinaFilePath, "mime_with_record_payload.yaml");
+    }
+
+    private String getStringFromGivenBalFile(Path expectedServiceFile, String s) throws IOException {
```
Comment (hemikak) [inline openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java:170]: Move this function to be after the `@AfterMethod` function

File: openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java [hunk 4]
```diff
@@ -165,12 +162,46 @@ public void testRecordFieldPayLoad() throws IOException, OpenApiConverterExcepti
...
+
+        Stream<String> expectedServiceLines = Files.lines(expectedServiceFile.resolve(s));
+        String expectedServiceContent = expectedServiceLines.collect(Collectors.joining("\n"));
+        expectedServiceLines.close();
+        return expectedServiceContent;
+    }
+
+    private void deleteGeneratedFiles(String filename) {
```
Comment (hemikak) [inline openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java:178]: Move this function to be after the `@AfterMethod` function

File: openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java (hunk 2 above)
Comment (hemikak) [inline openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java:186]: Move this function to be after the `@AfterMethod` function

**Review by hemikak — APPROVED** [review]
