### PR TITLE
Fix adding API documentation comments for client ` init` function

### LINKED ISSUE #367: Add API documentation comments for client init function
**Description:**
$Subject

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/main/java/io/ballerina/generators/client/BallerinaAuthConfigGenerator.java [hunk 1]
```diff
@@ -131,6 +131,10 @@ public boolean isHttpOROAuth() {
         return isHttpOROAuth;
     }
 
+    public boolean isAPIKey() {
+
```
Comment (LakshanSS) [inline openapi-cli/src/main/java/io/ballerina/generators/client/BallerinaAuthConfigGenerator.java:135]: Shall we remove this unwanted newline?

**Review by indikasampath2000 — APPROVED** [review]
